---
title: "First Montecarlo test"
author: "edm"
date: "8/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

library(MonteCarlo)
library(tidyverse)


```


```{r}
df_sample <- 1e3
```

## Area of the reservoir in km^2^

```{r echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE}


df <- 
  data.frame(area = runif( df_sample, 5, 12)) 
  
  
ggplot(df, aes(area))+
  geom_histogram(fill = "grey", bins = 20) +
  labs(x = "Area km2" ,
       y = "")+
  theme_minimal()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())




```

## Reservoir thickness in meters


```{r echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE}

df$thk  <-  runif(df_sample, 8, 17)
  
  
ggplot(df, aes(thk))+
  geom_histogram(fill = "grey", bins = 20) +
  labs(x = "Thickness in meters" ,
       y = "")+
  theme_minimal()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())


```


## Reservoir porosity in fraction


```{r echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE}

df$poro  <- rnorm(df_sample, 0.2, 0.03)
  
  
ggplot(df, aes(poro))+
  geom_histogram(fill = "grey", bins = 100) +
  labs(x = "Porosity in fraction" ,
       y = "")+
  theme_minimal()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())


```


## Reservoir water  saturation in fraction


```{r echo=FALSE, fig.height=5, fig.width=12, message=FALSE, warning=FALSE}

df$sw  <- rnorm(df_sample, 0.22, 0.04)
  
df<- df %>% mutate(sw = ifelse( sw < 0 , 0 ,  sw ) )
  
ggplot(df, aes(sw))+
  geom_histogram(fill = "grey", bins = 100) +
  labs(x = "Porosity in fraction" ,
       y = "")+
  theme_minimal()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())


```



```{r}


```


```{r}
mc_samples <- 1e5

mc_stooip <- data.frame(id = seq(1 , mc_samples  ))
for (i in 1:mc_samples) {
  mc_stooip[i,"stooip"]<- 
    sample(df$area, size = 1) * 
    1e6 *
    sample(df$thk, size = 1) *
    6.28*
     sample(df$poro, size = 1)*
     ( 1 - sample(df$sw, size = 1 )) 
    
}

ggplot(mc_stooip, aes(stooip/1e6))+
  geom_histogram()
```


